# Generated by Django 6.0.3 on 2026-04-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=14)),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
